Milestone : Create a data model
Kashif-Saleem-Ghuman/blog-app pull request #1
Opened 2023-03-29 18:22 UTC by Kashif-Saleem-Ghuman

In this milestone 💪 

- [ ] Created a new app with a meaningful name.
- [ ] Initialized project with Git.
- [ ] Postgres database is set up.
- [ ] -Built project schema.
- [ ] Create and run the necessary migration files.
- [ ] Foreign keys are included.
- [ ] In the posts table the column holding the foreign key to the users table is named author_id
- [ ] All columns that are foreign keys have a corresponding index.

2023-03-29 20:09 UTC, mikethreels requested changes
Hi Kashif, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 20:09 UTC, mikethreels commented on db/migrate/20230329175222_create_post.rb
> +    end
- [ ] please have a look at the ERD diagram as you can see the Post Table should have a column called likes_counter as well.
![afbeelding](https://user-images.githubusercontent.com/39240820/228655448-a9f9542e-2d2d-4f12-a20f-a10f270769d8.png)

2023-03-29 20:26 UTC, Kashif-Saleem-Ghuman commented
@mikethreels  Hi thank you for reviewing and pointing that out. 👍

2023-03-29 20:51 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Kashif-Saleem-Ghuman 

Your project is complete! Great job for making the changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- migration files ok
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 05:35 UTC, Kashif-Saleem-Ghuman commented
@tufoinnkuo10  Thank you for approving my PR 👍

2023-03-30 05:35 UTC, merged